[build]
  publish = "frontend/dist"
  command = "cd frontend && npm run build"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/resource"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/assignments"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/more"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/memorization"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
